"""add_activity_logs_ai_suggest

Revision ID: 7f80deaadccb
Revises: 
Create Date: 2026-06-30 15:50:24.529469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f80deaadccb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('activity_type', sa.Enum('lead_scraped', 'lead_qualified', 'lead_approved', 'lead_rejected', 'lead_updated', 'message_sent', 'message_received', 'ai_suggested', 'ai_sent', 'scrape_started', 'scrape_completed', 'instance_connected', 'instance_disconnected', 'appointment_booked', name='activitytype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_tenant_id'), 'activity_logs', ['tenant_id'], unique=False)
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_lead_stage', table_name='leads')
    op.drop_index('ix_lead_status', table_name='leads')
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.add_column('wa_instances', sa.Column('ai_suggest_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wa_instances', 'ai_suggest_enabled')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.create_index('ix_lead_status', 'leads', ['status'], unique=False)
    op.create_index('ix_lead_stage', 'leads', ['stage'], unique=False)
    op.drop_column('leads', 'last_contacted_at')
    op.drop_column('leads', 'notes')
    op.drop_index(op.f('ix_activity_logs_tenant_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
